# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-09 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tree_species', models.CharField(max_length=255)),
                ('diameter', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
